### ISSUE TITLE
Xiaomi Pen (gen-1) support?

### ISSUE THREAD

**Issue by Turtlepaw** [dev-harsh1998/android_device_xiaomi_nabu#6]
Hi, does this contain xiaomi pen gen-1 support?

**Comment by dev-harsh1998** [comment]
@Turtlepaw 
Yes, Both generations of pen & Xiaomi keyboard are supported by the builds made against the hosted device tree if you don't require support for gen2 pen just don't enable the toggle for it, Pens are supported via tha

custom hal: https://github.com/dev-harsh1998/android_device_xiaomi_nabu/tree/lineage-21/aidl/hwcontrol/custom/hardware/hwcontrol

Hal Impl: https://github.com/dev-harsh1998/android_device_xiaomi_nabu/tree/lineage-21/aidl/hwcontrol/rust_impl

Userspace java counterpart: https://github.com/dev-harsh1998/android_device_xiaomi_nabu/tree/lineage-21/aidl/hwcontrol/java_extension

Builds are released here: https://github.com/dev-harsh1998/ota/releases
and support updating to future version via OTA(s) unless explicitly mentioned otherwise.

Let's move the future discussion to the release repo[1] unless very serious issues are found. 

(1)  https://github.com/dev-harsh1998/ota
